# Generated by Django 5.1.2 on 2024-10-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['day', 'order']},
        ),
        migrations.AddField(
            model_name='period',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('day', 'order')},
        ),
    ]
