# Generated by Django 5.1.2 on 2024-10-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_period_options_period_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
