# Generated by Django 5.1.2 on 2024-10-19 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_slot', models.CharField(choices=[('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('02:00 - 03:00', '02:00 - 03:00'), ('03:00 - 04:00', '03:00 - 04:00')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.day')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'unique_together': {('course', 'day', 'period_slot')},
            },
        ),
    ]
